# Generated by Django 4.0.1 on 2022-01-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('titleEn', models.CharField(max_length=100)),
                ('titleEs', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('release', models.DateField()),
                ('rating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('episode', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('titleEn', models.CharField(max_length=100)),
                ('fansub', models.CharField(blank=True, max_length=100)),
                ('fsLink', models.CharField(blank=True, max_length=100)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.UUIDField(default='e14cc57982c54c3d885fdb9c336ee5cd', editable=False, unique=True)),
                ('render', models.ImageField(upload_to='media/render', verbose_name=models.UUIDField(default='e14cc57982c54c3d885fdb9c336ee5cd', editable=False, unique=True))),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.anime')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server', models.CharField(default='', max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.anime')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.UUIDField(default='7805617b98684689ac9e88d8bb20f4fc', editable=False, unique=True)),
                ('cover', models.ImageField(upload_to='media/cover', verbose_name=models.UUIDField(default='7805617b98684689ac9e88d8bb20f4fc', editable=False, unique=True))),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Anime_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.UUIDField(default='35f7d53828f84780a88c3124f19d048b', editable=False, unique=True)),
                ('background', models.ImageField(upload_to='media/background', verbose_name=models.UUIDField(default='35f7d53828f84780a88c3124f19d048b', editable=False, unique=True))),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.anime')),
            ],
        ),
    ]
