# Generated by Django 4.0.1 on 2022-01-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_background',
            name='background',
            field=models.ImageField(upload_to='media/background', verbose_name=models.UUIDField(default='7077199c5ef94199b6522192250a3561', editable=False, unique=True)),
        ),
        migrations.AlterField(
            model_name='anime_background',
            name='filename',
            field=models.UUIDField(default='7077199c5ef94199b6522192250a3561', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime_cover',
            name='cover',
            field=models.ImageField(upload_to='media/cover', verbose_name=models.UUIDField(default='00cdd272b17e4c599162419ee57acd9b', editable=False, unique=True)),
        ),
        migrations.AlterField(
            model_name='anime_cover',
            name='filename',
            field=models.UUIDField(default='00cdd272b17e4c599162419ee57acd9b', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime_render',
            name='filename',
            field=models.UUIDField(default='1a8f074545f44c30ad221d7c7e398249', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime_render',
            name='render',
            field=models.ImageField(upload_to='media/render', verbose_name=models.UUIDField(default='1a8f074545f44c30ad221d7c7e398249', editable=False, unique=True)),
        ),
        migrations.CreateModel(
            name='Episode_thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.UUIDField(default='4804750b3fd641958acae08024a77588', editable=False, unique=True)),
                ('thumbnail', models.ImageField(upload_to='media/thumbnail', verbose_name=models.UUIDField(default='4804750b3fd641958acae08024a77588', editable=False, unique=True))),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utama.episode')),
            ],
        ),
    ]
