# Generated by Django 4.0.1 on 2022-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0002_alter_anime_backgroundfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='backgroundFilename',
            field=models.UUIDField(default='ef8e08fe9b904ab59185a0fa36d28c07', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='coverFilename',
            field=models.UUIDField(default='c4a7b59cf1b9479ca65b500f1fe9fab1', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='renderFilename',
            field=models.UUIDField(default='10bb0bac7d024674b796e94ccd830617', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ThumbnailFilename',
            field=models.UUIDField(default='2e6def5df27f432f89b163beca743e1e', editable=False, unique=True),
        ),
    ]
