# Generated by Django 4.0.1 on 2022-01-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0003_alter_anime_backgroundfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='backgroundFilename',
            field=models.UUIDField(default='303fb6a6a5ae499c98a6396aef5ac398', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='coverFilename',
            field=models.UUIDField(default='7352e6a63c8140d18c640d0ac9d94b8e', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='renderFilename',
            field=models.UUIDField(default='bd06eb07e00e4495b63e030a5d6c734f', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ThumbnailFilename',
            field=models.UUIDField(default='9b543be9a65d4f948078ae7570399107', editable=False, unique=True),
        ),
    ]
