# Generated by Django 4.0.1 on 2022-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0004_alter_anime_backgroundfilename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='is_premiere',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='backgroundFilename',
            field=models.UUIDField(default='4214c5e702004294a387f50e8d7330a5', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='coverFilename',
            field=models.UUIDField(default='8f5c88f3d7ee48c6abc07092d33554ed', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='renderFilename',
            field=models.UUIDField(default='4285c5f176624c0eac3540afd9b8c553', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ThumbnailFilename',
            field=models.UUIDField(default='78bc96a361bf4826a7d4ceeaa4d93e23', editable=False, unique=True),
        ),
    ]
