# Generated by Django 4.0.1 on 2022-01-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0005_episode_is_premiere_alter_anime_backgroundfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='backgroundFilename',
            field=models.UUIDField(default='b89341acc6114da5bbbc40cec6257bbc', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='coverFilename',
            field=models.UUIDField(default='00b4f01fb6eb46139fa966fc85c32f55', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='renderFilename',
            field=models.UUIDField(default='a3e5f298ad8f442c95cb54990ee9e42a', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ThumbnailFilename',
            field=models.UUIDField(default='ce33ef8218cf4d948a7a24563cb253ce', editable=False, unique=True),
        ),
    ]
