# Generated by Django 4.0.1 on 2022-01-13 12:39

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0006_alter_anime_backgroundfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='backgroundFilename',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='coverFilename',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='renderFilename',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='animeepisode',
            name='episode',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='anime', chained_model_field='anime', on_delete=django.db.models.deletion.CASCADE, to='utama.episode'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ThumbnailFilename',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
