# Generated by Django 4.0.1 on 2022-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0007_alter_anime_backgroundfilename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release',
            field=models.DateTimeField(),
        ),
    ]
