# Generated by Django 4.0.1 on 2022-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utama', '0008_alter_anime_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='titleEn',
        ),
        migrations.AlterField(
            model_name='animeepisode',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
